apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  finalizers: 
  - resources-finalizers.argocd.argoproj.io
  name: canales
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: openshift-gitops
    server: https://kubernetes.default.svc
  - namespace: canales-prod
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceBlacklist:
  - group: ''
    kind: NetworkPolicy
---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: solar-system
  namespace: canales-prod
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: canales-prod
    server: https://kubernetes.default.svc
  project: canales
  source:
    path: ./
    repoURL: https://github.com/tatimun/solar-system
    targetRevision: main
