apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: canales
  namespace: openshift-gitops
spec:
  sourceRepos:
  - '*'
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceBlacklist:
  - group: ''
    kind: NetworkPolicy
