apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: canales
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: Namespace
  - group: argoproj.io
    kind: Application
  - group: argoproj.io
    kind: AppProject
  - group: argoproj.io
    kind: ApplicationSet
  - group: '*'
    kind: Secret
  - group: '*'
    kind: PersistentVolumeClaim
  - group: '*'
    kind: Pipeline
  - group: '*'
    kind: ServiceAccount
  - group: '*'
    kind: LimitRange
  - group: '*'
    kind: ResourceQuota
  - group: '*'
    kind: ClusterTask
  destinations:
  - namespace: openshift-gitops
    server: https://kubernetes.default.svc
  - namespace: canales-prod
    server: https://kubernetes.default.svc
  namespaceResourceBlacklist:
  - group: ''
    kind: NetworkPolicy
  sourceRepos:
  - '*'
